package com.example.bundesligaapp.pojo

data class Venue(
    val idDupe: Any?,
    val idVenue: String?,
    val intCapacity: String?,
    val intFormedYear: String?,
    val strArchitect: Any?,
    val strCost: String?,
    val strCountry: String?,
    val strDescriptionEN: String?,
    val strFacebook: String?,
    val strFanart1: String?,
    val strFanart2: String?,
    val strFanart3: String?,
    val strFanart4: String?,
    val strInstagram: String?,
    val strLocation: String?,
    val strLocked: String?,
    val strLogo: String?,
    val strMap: String?,
    val strSport: String?,
    val strThumb: String?,
    val strTimezone: String?,
    val strTwitter: String?,
    val strVenue: String?,
    val strVenueAlternate: String?,
    val strVenueSponsor: String?,
    val strWebsite: String?,
    val strYoutube: String?
)
